AWSTemplateFormatVersion: 2010-09-09
Description: Live System Log Analysis and Visualization CSC 591 DIC
Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    ConstraintDescription: EC2 instance tupe must be a supported.
  KeyName:
    Description: >-
      (Optional) Name of an existing EC2 KeyPair to enable SSH access to the
      instance. If this is not provided you will not be able to SSH on to the
      EC2 instance.
    Type: String
    Default: 'live_log'
    MinLength: '0'
    MaxLength: '255'
    AllowedPattern: '[\x20-\x7E]*'
    ConstraintDescription: can contain only ASCII characters.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  # ApplicationArchive:
  #   Description: >-
  #     A publicly accessible URL to the sample application archive as produced by
  #     'mvn package'
  #   Type: String
  #   MinLength: '7'
  #   MaxLength: '255'
  #   Default: >-
  #     https://github.com/awslabs/amazon-kinesis-data-visualization-sample/releases/download/v1.1.1/amazon-kinesis-data-visualization-sample-1.1.1-assembly.zip
Conditions:
  UseEC2KeyName: !Not 
    - !Equals 
      - !Ref KeyName
      - ''
Mappings:
  AWSInstanceType2Arch:
    t2.micro:
      Arch: '64'
  AWSRegionArch2AMI:
    us-west-2:
      '64': ami-0bbe6b35405ecebdb
Resources:
  KinesisStream:
    Type: 'AWS::Kinesis::Stream'
    Properties:
      ShardCount: '2'
  KCLDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: leaseKey
          AttributeType: S
      KeySchema:
        - AttributeName: leaseKey
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '5'
  CountsDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: resource
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: resource
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '5'
  Ec2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access and HTTP access on the inbound port
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
  EIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: !Ref Ec2Instance
  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
  RolePolicies:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: root
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 'kinesis:*'
            Resource: !Join 
              - ''
              - - 'arn:aws:kinesis:'
                - !Ref 'AWS::Region'
                - ':'
                - !Ref 'AWS::AccountId'
                - ':stream/'
                - !Ref KinesisStream
          - Effect: Allow
            Action: 'dynamodb:*'
            Resource: !Join 
              - ''
              - - 'arn:aws:dynamodb:'
                - !Ref 'AWS::Region'
                - ':'
                - !Ref 'AWS::AccountId'
                - ':table/'
                - !Ref KCLDynamoDBTable
          - Effect: Allow
            Action: 'dynamodb:*'
            Resource: !Join 
              - ''
              - - 'arn:aws:dynamodb:'
                - !Ref 'AWS::Region'
                - ':'
                - !Ref 'AWS::AccountId'
                - ':table/'
                - !Ref CountsDynamoDBTable
          - Effect: Allow
            Action: 'cloudwatch:*'
            Resource: '*'
      Roles:
        - !Ref RootRole
  RootInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref RootRole
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Metadata:
      'AWS::CloudFormation::Init':
        config:
          packages:
            yum:
              java-1.7.0-openjdk: []
              python3: []
          # files:
          #   /var/kinesis-data-vis-sample-app/watchdog.sh:
          #     content: !Join 
          #       - ''
          #       - - |
          #           #!/bin/bash
          #         - >
          #           if ! ps aux | grep HttpReferrerCounterApplication | grep -v
          #           grep ; then
          #         - |2
          #               # Launch the Kinesis application for counting HTTP referrer pairs
          #         - '    java -cp /var/kinesis-data-vis-sample-app/lib/\* com.amazonaws.services.kinesis.samples.datavis.HttpReferrerCounterApplication '
          #         - !Ref KCLDynamoDBTable
          #         - ' '
          #         - !Ref KinesisStream
          #         - ' '
          #         - !Ref CountsDynamoDBTable
          #         - ' '
          #         - !Ref 'AWS::Region'
          #         - |2
          #            &>> /home/ec2-user/kinesis-data-vis-sample-app-kcl.log &
          #         - |
          #           fi
          #         - >
          #           if ! ps aux | grep HttpReferrerStreamWriter | grep -v grep ;
          #           then
          #         - |2
          #               # Launch our Kinesis stream writer to fill our stream with generated HTTP (resource, referrer) pairs.
          #         - |2
          #               # This will create a writer with 5 threads to send records indefinitely.
          #         - '    java -cp /var/kinesis-data-vis-sample-app/lib/\* com.amazonaws.services.kinesis.samples.datavis.HttpReferrerStreamWriter 5 '
          #         - !Ref KinesisStream
          #         - ' '
          #         - !Ref 'AWS::Region'
          #         - |2
          #            &>> /home/ec2-user/kinesis-data-vis-sample-app-publisher.log &
          #         - |
          #           fi
          #         - |
          #           if ! ps aux | grep WebServer | grep -v grep ; then
          #         - |2
          #               # Launch the webserver
          #         - '    java -cp /var/kinesis-data-vis-sample-app/lib/\* com.amazonaws.services.kinesis.samples.datavis.WebServer 80 /var/kinesis-data-vis-sample-app/wwwroot '
          #         - !Ref CountsDynamoDBTable
          #         - ' '
          #         - !Ref 'AWS::Region'
          #         - |2
          #            &>> /home/ec2-user/kinesis-data-vis-sample-app-www.log &
          #         - |
          #           fi
          #     mode: '000755'
          #     owner: ec2-user
          #     group: ec2-user
          #   /var/kinesis-data-vis-sample-app/crontask:
          #     content: !Join 
          #       - ''
          #       - - |
          #           * * * * * bash /var/kinesis-data-vis-sample-app/watchdog.sh
          #     mode: '000644'
          #     owner: ec2-user
          #     group: ec2-user
          # sources:
          #   /var/kinesis-data-vis-sample-app: !Ref ApplicationArchive
    Properties:
      KeyName: !If 
        - UseEC2KeyName
        - !Ref KeyName
        - !Ref 'AWS::NoValue'
      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref Ec2SecurityGroup
      IamInstanceProfile: !Ref RootInstanceProfile
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash
            - |
                echo 'UserData Automation Script'
            # - |
            #   yum update -y aws-cfn-bootstrap
            # - '/opt/aws/bin/cfn-init -s '
            # - !Ref 'AWS::StackId'
            # - ' -r Ec2Instance '
            # - '         --region '
            # - !Ref 'AWS::Region'
            # - |+

            # - |
            #   # Register watchdog script with cron
            # - |
            #   crontab /var/kinesis-data-vis-sample-app/crontask
            # - >
            #   # Launch watchdog script immediately so if it fails this stack
            #   fails to start
            # - |
            #   /var/kinesis-data-vis-sample-app/watchdog.sh
            # - /opt/aws/bin/cfn-signal -e $? '
  #           - !Ref WaitHandle
  #           - |
  #             '
  # WaitHandle:
  #   Type: 'AWS::CloudFormation::WaitConditionHandle'
  # WaitCondition:
  #   Type: 'AWS::CloudFormation::WaitCondition'
  #   DependsOn: Ec2Instance
  #   Properties:
  #     Handle: !Ref WaitHandle
  #     Timeout: '600'
Outputs:
  URL:
    Description: URL to the sample application's visualization
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - Ec2Instance
          - PublicDnsName
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref Ec2Instance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt 
      - Ec2Instance
      - AvailabilityZone
  StreamName:
    Description: >-
      The name of the Kinesis Stream. This was autogenerated by the Kinesis
      Resource named 'KinesisStream'
    Value: !Ref KinesisStream
  ApplicationName:
    Description: >-
      The name of the Kinesis Client Application. This was autogenerated by the
      DynamoDB Resource named 'KCLDynamoDBTable'
    Value: !Ref KCLDynamoDBTable
  CountsTable:
    Description: >-
      The name of the DynamoDB table where counts are persisted. This was
      autogenerated by the DynamoDB Resource named 'CountsDynamoDBTable'
    Value: !Ref CountsDynamoDBTable
