datafile='raw/weblog.csv'
min_delay_record=100  #ms
max_delay_record=1500  #ms
min_delay_response=0  #ms
max_delay_response=700  #ms
stream_name = 'LiveLog2-KinesisStream-DBEK4VO0R1HJ'
region_name='us-west-2'
window_size = 5
table_name = 'LiveLog2-CountsDynamoDBTable-1WY5HDM9TS6I6'
