MyStream:
  Type: AWS::Kinesis::Stream
  Properties:
    Name: MyKinesisStream
    RetentionPeriodHours: 168
    ShardCount: 3
    StreamEncryption:
        EncryptionType: KMS
        KeyId: !Ref myKey
    Tags:
      -
        Key: Environment
        Value: Production
