AWSTemplateFormatVersion: 2010-09-09
Description: Live System Log Analysis and Visualization CSC 591 DIC - Create EC2 Instance
Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    ConstraintDescription: EC2 instance supported type
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access.
      instance. 
    Type: String
    Default: 'live_log'
    MinLength: '0'
    MaxLength: '255'
    AllowedPattern: '[\x20-\x7E]*'
    ConstraintDescription: ASCII Chars
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances.
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Conditions:
  UseEC2KeyName: !Not 
    - !Equals 
      - !Ref KeyName
      - ''

Mappings:
  AWSInstanceType2Arch:
    t2.micro:
      Arch: '64'
  AWSRegionArch2AMI:
    us-west-2:
      '64': ami-0bbe6b35405ecebdb

Resources:
  Ec2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: For inbound port, enable SSH access and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
  EIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: !Ref Ec2Instance
  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
  RootInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref RootRole
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Metadata:
      'AWS::CloudFormation::Init':
        config:
          packages:
            yum:
              python3: []
    Properties:
      KeyName: !If 
        - UseEC2KeyName
        - !Ref KeyName
        - !Ref 'AWS::NoValue'
      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref Ec2SecurityGroup
      IamInstanceProfile: !Ref RootInstanceProfile

Outputs:
  URL:
    Description: EC2 instance URL for visualization
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - Ec2Instance
          - PublicDnsName
