AWSTemplateFormatVersion: 2010-09-09
Description: Consumers DynamoDB data for further analysis and feedback

Resources:
  LogsDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: endpoint
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: endpoint
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '5'

Outputs:
  CountsTable:
    Description: Logs for consumers stored in NoSQL for further analysis and feedback loop
    Value: !Ref LogsTableDynamoDB
